sudo: false
dist: trusty
language: java

os:
- linux
- osx

before_install:
# https://github.com/travis-ci/travis-ci/issues/8408
- unset -v _JAVA_OPTIONS

install:
- . ./install-jdk.sh

script:
- java --version
- ./build.jsh

after_success:
- cd $TRAVIS_BUILD_DIR/demo/00-bootstrap
- ./bootstrap.jsh

- cd $TRAVIS_BUILD_DIR/demo/01-hello-world
- ./build-01-hello-world.jsh
