sudo: false
language: java

before_install:
- unset -v _JAVA_OPTIONS
- wget https://github.com/sormuras/bach/raw/support-older-jdks/install-jdk.sh

matrix:
  include:
  - env: Java='5'
  - env: Java='6'
  - env: Java='7'
  - env: Java='8'
  - env: Java='9'
  - env: Java='10'
  - env: Java='11'

install:
- source ./install-jdk.sh --verbose --resurrect --feature ${Java}

script:
- echo PATH = ${PATH}
- echo JAVA_HOME = ${JAVA_HOME}
- java -version
