sudo: false
language: java

before_install:
- unset -v _JAVA_OPTIONS

before_install:
  - wget https://github.com/sormuras/bach/raw/support-older-jdks/install-jdk.sh

matrix:
  include:
    - env: JDK='JDK 5'
      install: . ./install-jdk.sh --verbose --feature 5

    - env: JDK='JDK 6'
      install: . ./install-jdk.sh --verbose --feature 6

    - env: JDK='JDK 7'
      install: . ./install-jdk.sh --verbose --feature 7

    - env: JDK='JDK 8'
      install: . ./install-jdk.sh --verbose --feature 8

    - env: JDK='JDK 9'
      install: . ./install-jdk.sh --verbose --feature 9

    - env: JDK='JDK 10'
      install: . ./install-jdk.sh --verbose --feature 10

    - env: JDK='JDK 11'
      install: . ./install-jdk.sh --verbose --feature 11

script:
- echo PATH = ${PATH}
- echo JAVA_HOME = ${JAVA_HOME}
- java -version
