sudo: false
dist: trusty
language: java

#os:
#- linux
#- osx

before_install:
# https://github.com/travis-ci/travis-ci/issues/8408
- unset -v _JAVA_OPTIONS
# https://github.com/travis-ci/travis-ci/issues/8703
- unset -f cd

install:
# HotSpot
# - . ./install-jdk.sh --verbose --url $(curl --silent https://api.adoptopenjdk.net/openjdk10/nightly/x64_linux/latest/ | grep 'binary_link' | grep -Eo '(http|https)://[^"]+')

# OpenJ9
- . ./install-jdk.sh --verbose --url $(curl --silent https://api.adoptopenjdk.net/openjdk10-openj9/nightly/x64_linux/latest/ | grep 'binary_link' | grep -Eo '(http|https)://[^"]+')

script:
- java --version
- ./build.jsh

#after_success:
#- cd $TRAVIS_BUILD_DIR/demo/00-bootstrap
#- ./bootstrap.jsh
#
#- cd $TRAVIS_BUILD_DIR/demo/01-hello-world
#- ./build-01-hello-world.jsh
